// Generated by CoffeeScript 2.3.2
(function() {
  // create a PlayCanvas application
  var app, camera, canvas, cube, light;

  canvas = document.getElementById('application');

  app = new pc.Application(canvas, {});

  app.start();

  // fill the available space at full resolution
  app.setCanvasFillMode(pc.FILLMODE_FILL_WINDOW);

  app.setCanvasResolution(pc.RESOLUTION_AUTO);

  // ensure canvas is resized when window changes size
  window.addEventListener('resize', function() {
    return app.resizeCanvas();
  });

  // create box entity
  cube = new pc.Entity('cube');

  cube.addComponent('model', {
    type: 'box'
  });

  // create camera entity
  camera = new pc.Entity('camera');

  camera.addComponent('camera', {
    clearColor: new pc.Color(0.1, 0.1, 0.1)
  });

  // create directional light entity
  light = new pc.Entity('light');

  light.addComponent('light');

  // add to hierarchy
  app.root.addChild(cube);

  app.root.addChild(camera);

  app.root.addChild(light);

  // set up initial positions and orientations
  camera.setPosition(0, 0, 3);

  light.setEulerAngles(45, 0, 0);

  // register a global update event
  app.on('update', function(deltaTime) {
    return cube.rotate(10 * deltaTime, 20 * deltaTime, 30 * deltaTime);
  });

}).call(this);
